name: Rust building

on:
  push:
    branches: [master]
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.75.0

        env:
          SQLX_OFFLINE: true
      - uses: actions-rs/cargo@v1
        name: Build program
        with:
          command: build
